### ISSUE TITLE
Create static-linked build?

### ISSUE THREAD

**Issue by emendelson** [gs11/dosbox-macbuild#2]
This is just wonderful. Thank you. Is there any hope that the script might be able to create a static-linked build? Using techniques provided by "dominus" at Vogons.org, I put together a much more incompetent script than yours, but it was able to create a static-linked executable through a complicated kludge.

If you have a way to create a static-linked build, that would be terrific. But I know it may not be worth the effort.

**Comment by gs11** [comment]
Hi, I'm very unfamiliar with the world of GCC et al but I found your post on vogons.org. To my understanding, SDL is already statically linked. See otool output on dynamically linked libs:
```
gsMac:MacOS gs$ otool -L DOSBox 
DOSBox:
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 157.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI (compatibility version 1.0.0, current version 69.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1504.83.101)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.90.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1070.22.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 775.19.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1349.91.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

```

**Comment by emendelson** [comment]
**Edit: Problem solved. See next message.**

Thank you for the quick reply. I'm completely puzzled by this, because this is the result I get:

> MacBook-Air-2015:MacOS edward$ otool -L DOSBox
DOSBox:
	/usr/local/lib/libSDL-1.2.0.dylib (compatibility version 12.0.0, current version 12.4.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI (compatibility version 1.0.0, current version 69.0.0)
	/System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.40.112)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1161.10.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)


I built on an up-to-date High Sierra system, but for some reason I'm getting SDL linked dynamically (as you see from the first line). The executable that I get is 3.3MB. Presumably yours is larger?

I don't pretend to understand any of this, but this is very odd...!

**Comment by emendelson** [comment]
I'll leave that earlier message in case someone could use it - but it turns out that the answer is simple (though I still don't understand it).

I solved this problem by renaming /usr/local/lib/libSDL-1.2.0.dylib and /usr/local/bin/sdl-config. When I did that, your script created a static-linked executable. Apparently, if SDL 1.2 is installed in the system, Xcode creates a dynamic-linked executable. I wonder if there's a way to prevent this from happening?

**Comment by gs11** [comment]
I'm guessing that you could force gcc to use statically link to SDL rather than getting the one installed in the system. I'm guessing there'd be some parameter for the dosbox configure command to achieve this.

**Comment by emendelson** [comment]
Dominus on Vogons.org has a very elaborate makefile patch that forces static-linking; I use his technique in my own script (which I've now retired in favor of a modified version of yours). There doesn't seem to be a simple configure switch that does this. Meanwhile, this message thread tells the answer for anyone who might need it.
