### ISSUE TITLE
Mojave 10.14 compatibility

### ISSUE THREAD

**Issue by almeath** [gs11/dosbox-macbuild#3]
Thanks for your work on this. When I try building in Mojave 10.14, DOSBox will launch but then only show a white screen. Not sure what is going on because the build itself seems to work flawlessly and there are no errors in the terminal output.

Are there any dependencies that need to be updated for Mojave compatibility?

**Comment by gs11** [comment]
Unfortunately I don't have Mojave to test but maybe this thread can be of help? https://www.vogons.org/viewtopic.php?t=61123&p=683622

**Comment by almeath** [comment]
It looks like that might be a similar symptom caused by an unrelated issue, as it was an error reported in the Windows version of DOSBox. 

At the moment I am fine with using the version I previously built in High Sierra 10.13, which still works when I bring it across to Mojave. It is only when I build from scratch in Mojave that this problem occurs. I am happy to wait until you get a chance to test in a Mojave system.
